### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by StefanCohen** [ChrisHaPunkt/stihl-imow-webapi#8]
The updated usage example in README.md returns the following error since the switch to asyncio: 

```
Traceback (most recent call last):
  File "imowstats.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "imowstats.py", line 10, in main
    token, expire_time = await api.get_token("somename@gmail.com", "hunter2", return_expire_time=True)
  File "/usr/local/lib/python3.8/dist-packages/imow/api/__init__.py", line 85, in get_token
    await self.__authenticate(self.api_email, self.api_password)
  File "/usr/local/lib/python3.8/dist-packages/imow/api/__init__.py", line 117, in __authenticate
    await self.__fetch_new_csrf_token_and_request_id()
  File "/usr/local/lib/python3.8/dist-packages/imow/api/__init__.py", line 151, in __fetch_new_csrf_token_and_request_id
    response = await self.api_request(url, "GET")
  File "/usr/local/lib/python3.8/dist-packages/imow/api/__init__.py", line 203, in api_request
    return await self.http_session.request(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 448, in _request
    with timer:
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 635, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f772b34d4c0>
```

Python 3.8.5
imow-webapi: 0.4.4
asyncio: 3.4.3

Setting the PYTHONASYNCIODEBUG=1 env var will yield some more debug info.

**Comment by ChrisHaPunkt** [comment]
Unfortunately I'm currently not able to validate and test my resolving PR because the imow api server is under maintenance. But this should make the example run again.

**Comment by ChrisHaPunkt** [comment]
Please reopen if you still faces the error

**Comment by StefanCohen** [comment]
Confirmed working. Thanks!
